<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="helios">

    <xacro:property name="camera_pole_width" value="0.03"/>
    <xacro:property name="camera_pole_height" value="0.6"/>
    <xacro:property name="camera_pole_mass" value="0.01"/>

    <xacro:property name="zed2i_length" value="0.28"/>
    <xacro:property name="zed2i_width" value="0.03"/>
    <xacro:property name="zed2i_height" value="0.03"/>
    <xacro:property name="zed2i_mass" value="0.01"/>


    <!-- CAMERA LINK -->
    <!-- camera pole -->
    <joint name="camera_pole_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="camera_pole_link"/>
        <origin xyz="${camera_pole_width/2} 0 ${chassis_height}"/>
    </joint>

    <link name="camera_pole_link">
        <visual>
            <origin xyz="0 0 ${camera_pole_height/2}"/>
            <geometry>
                <box size="${camera_pole_width} ${camera_pole_width} ${camera_pole_height}"/> 
            </geometry>
             <material name="red"/>
        </visual>

        <collision>
            <origin xyz="0 0 ${camera_pole_height/2}"/>
            <geometry>
                <box size="${camera_pole_width} ${camera_pole_width} ${camera_pole_height}"/> 
            </geometry>
        </collision>

        <xacro:inertial_box mass="${camera_pole_mass}" x="0" y="0" z="${camera_pole_height/2}">
            <origin xyz="0 0 ${camera_pole_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- zed2i camera -->
    <joint name="zed2i_joint" type="fixed">
        <parent link="camera_pole_link"/>
        <child link="zed2i_link"/>
        <origin xyz="0 0 ${camera_pole_height}"/>
    </joint>

    <link name="zed2i_link">
        <visual>
            <origin xyz="0 0 ${zed2i_height/2}"/>
            <geometry>
                <box size="${zed2i_width} ${zed2i_length} ${zed2i_height}"/>
            </geometry>
            <material name="black"/>
        </visual>

        <collision>
            <origin xyz="0 0 ${zed2i_height/2}"/>
            <geometry>
                <box size="${zed2i_width} ${zed2i_length} ${zed2i_height}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${zed2i_mass}" x="0" y="0" z="${zed2i_height/2}">
            <origin xyz="0 0 ${zed2i_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

</robot>